@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

class Duke
interface Bot INTERFACE_COLOR
class DukeChatBot

package logic {

    package command {
        class XYZCommand
        class "{abstract}\nCommand" as Command ABSTRACT_CLASS
    }

    package parser {
        class XYZCommandParser
        class StorageParser
        interface CommandParser INTERFACE_COLOR
        interface Parser INTERFACE_COLOR
        interface StorageCommandParser INTERFACE_COLOR
        class DukeParser
    }

}

package storage {
    interface Storage INTERFACE_COLOR
    class DukeStorage
}

package model{
    interface TaskList INTERFACE_COLOR
    class DukeTaskList
}





Duke .down.> Bot
Bot <|.down. DukeChatBot

DukeChatBot -left-> Parser
DukeChatBot -right-> TaskList
DukeChatBot -down-> Storage

DukeTaskList .down.|> TaskList

DukeStorage .up.|> Storage
DukeStorage -left-> Parser
DukeStorage .right.> TaskList
DukeStorage .down.> Command

DukeParser .down.> XYZCommandParser
DukeParser .right.> Command
DukeParser .right.|> Parser
StorageParser .down.|> Parser

XYZCommandParser .down.|> CommandParser
XYZCommandParser .down.> XYZCommand
XYZCommandParser .left.|> StorageCommandParser
XYZCommand -down-|> Command


@enduml
