@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

class Duke
interface Bot INTERFACE_COLOR
class DukeChatBot

package logic {

    package command {
        class XYZCommand
        class "{abstract}\nCommand" as Command ABSTRACT_CLASS
    }

    package parser {
        class XYZCommandParser
        interface Parser INTERFACE_COLOR
        class DukeParser
    }

}

package storage {
    interface Storage INTERFACE_COLOR
    class DukeStorage
}

package model{
    interface TaskList INTERFACE_COLOR
    class DukeTaskList
}





Duke .right.> Bot
Bot <|.right. DukeChatBot
DukeChatBot -down-> DukeParser
DukeChatBot -right-> TaskList
DukeChatBot --> Storage

DukeTaskList <|.left. TaskList

DukeStorage <|.right. Storage

DukeParser .down.> XYZCommandParser
DukeParser .right.> Command

XYZCommandParser .left.|> Parser
XYZCommandParser .right.> XYZCommand
XYZCommand -up-|> Command


@enduml
